Add visuals to 2021-09-30-data-maturity-open-source.md
MERLTech/MERL-Center-public pull request #90
Opened 2022-10-11 01:08 UTC by hanisahkz

This PR is for content, "[Leveraging Open Source Software to Build a Data Mature Ecosystem in the Social Sector: An Introduction](https://merlcenter.org/guides/data-maturity-open-source/)" and covers the following:

* **Main:** Add visuals to certain section
  * Spreadsheet for tracking can be found [here](https://docs.google.com/spreadsheets/d/15baCjqrkHPMRjrvJ599_7ToDnnQb7EElMxVRu1u6rX4/edit?usp=sharing).  
* **Others:**
  * Added anchor to `Table 1` to improve reading experience
  * Added improvement to use proper title case capitalization (based on APA [style guide](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case))
* See comparison table below for reference on how it gets rendered (the impacted area is highlighted in 🟪 :

| Current        |       PR       |
|----------------|:--------------:|
| ![Screenshot 2022-10-11 at 08-16-53 Leveraging Open Source Software to Build a Data Mature Ecosystem in the Social Sector An Introduction](https://user-images.githubusercontent.com/20330038/194974207-07574446-9c45-4b5f-b846-a9eb1731e1cc.png) | ![Screenshot 2022-10-11 at 08-51-22 Leveraging Open Source Software to Build a Data Mature Ecosystem in the Social Sector An Introduction](https://user-images.githubusercontent.com/20330038/194974367-5a8f25ac-8a01-4e06-8df6-cff4fa475839.png) |

2022-10-11 01:12 UTC, hanisahkz commented on _guides/2021-09-30-data-maturity-open-source.md
> +| <img src="/assets/img/posts/v1-data-orchard-data-kind-mf.png" alt="Data Kind-Data Orchard maturity framework" width="250"> | [Data Orchard’s and DataKind UK’s framework](https://drive.google.com/fi
I'm using HTML here as it provides better flexibility when customizing the visuals (size, position, etc). I noticed that some other content can also use this approach. Example: https://merlcenter.org/guides/open-source-merl-workflows/

2022-10-11 16:04 UTC, ronna reviewed
Looks good to me.

2022-10-13 14:22 UTC, scoker-me commented
thanks. @hanisahkz  I think those changes look good in general but think we should change or move the text overlapping the infinity symbol so it's easier to read. was this made in Google Data Studio?

2022-10-24 08:06 UTC, hanisahkz commented
> thanks. @hanisahkz I think those changes look good in general but think we should change or move the text overlapping the infinity symbol so it's easier to read. 

Agreed. I have updated the image used. In the blog, it will look like this:
 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/20330038/197477359-909417d7-fbc7-4a48-ad41-f88323ee47b0.png">
 

> was this made in Google Data Studio?

Nope. For this one, I'm using Affinity Designer to re-create the loop and customize the design.

2022-10-26 03:46 UTC, bonniewolfe requested changes
Can we replace the MERL Center logo with the Care logo?
https://www.care.org/wp-content/uploads/2021/01/primary_logo_horizontal_min.svg

2022-10-26 16:02 UTC, hanisahkz commented
> Can we replace the MERL Center logo with the Care logo? https://www.care.org/wp-content/uploads/2021/01/primary_logo_horizontal_min.svg

Sure! I've amended as requested. 

Just in case this wasn't considered - Initially, I wanted to add CARE's logo. However, I was unsure due to their T&C: [https://www.care.org/terms-of-use/](https://www.google.com/url?q=https://www.care.org/terms-of-use/&sa=D&source=editors&ust=1666802628665480&usg=AOvVaw2QAYw-yPmWksE4pXpdtDki). We can can email them about using their logo.

2022-12-07 19:00 UTC, scoker-me approved these changes

2022-12-07 19:05 UTC, scoker-me approved these changes

2022-12-07 19:06 UTC, scoker-me commented
> > Can we replace the MERL Center logo with the Care logo? https://www.care.org/wp-content/uploads/2021/01/primary_logo_horizontal_min.svg
> 
> Sure! I've amended as requested.
> 
> Just in case this wasn't considered - Initially, I wanted to add CARE's logo. However, I was unsure due to their T&C: [https://www.care.org/terms-of-use/](https://www.google.com/url?q=https://www.care.org/terms-of-use/&sa=D&source=editors&ust=1666802628665480&usg=AOvVaw2QAYw-yPmWksE4pXpdtDki). We can can email them about using their logo.

Since our content is only for educational purposes, I think we can go ahead and include.

2022-12-07 19:06 UTC, merged